service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  profile: serverless-admin

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello-lamdba
          method: get
